language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  postgresql: "9.5"
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      - libcups2-dev # for aeroo
      # FE
      - python-dev
      - swig
      - libffi-dev
      - libssl-dev
      - python-m2crypto
      - python-httplib2

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  - PHANTOMJS_VERSION="latest"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
#  - TESTS="1" ODOO_REPO="OCA/OCB"

install:
  - pip install codecov
  - pip install -r requirements.txt
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - git clone --depth=1 https://github.com/reingart/pyfiscalprinter.git /usr/local/lib/python2.7/dist-packages/pyfiscalprinter


script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
  - codecov